### ISSUE TITLE
Installing data into /usr/local/share

### ISSUE THREAD

**Issue by nms-scribe** [fosskers/cargo-aur#19]
My project includes some data (mostly sample files) which I would like my aur package to install into `/usr/local/share/<appname>`. Can cargo-aur be configured to include these files in the tar file in a way that they would be copied into the right place on install?

**Comment by fosskers** [comment]
That's a reasonable request. Perhaps something like:
```toml
[package.metadata.aur]
files = [
  ["/path/to/original/file", "/absolute/path/to/desired/location"],
  # ... and so on ...
]
```
